### ISSUE TITLE
Setup: feedback for new version (with org secrets)

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-ALAutomatedTestingTests#150]
Feedback about set up interview version in PR #149

Only got to the page asking about account info for secrets.

# Who are you?
- "What you can do depends on..." - What you can do with tests? What you can do in this set up process? Thinks the latter.
   - [x] change to "What you can set up depends on..."

# What do you want to do?
- Is not sure that non-admin can set up secrets. Secrets seems like an admin thing.
   - [x] [Added conditional language about getting your org admin to set things up] Maybe change text about org for non-admin: It might be useful to get your org admin set up secrets.
   - [x] [Stated role and what that role is able to do at the top of the question] Reassure somehow? "Any person who can change files on the repository can set up "secrets"."
- [x] [Moved info to help screen that is linked many times in the interview] Info about how tool works may just be confusing here
   - Note: will still need to know this if setting up own secrets
- [x] [Changed where the information was being given, attempted to take smaller steps to walk people through understanding the situation] Note: Too much technobable maybe. Or maybe info given at the wrong time
- [x] Note: Help button is not noticeable enough. Wasn't noticed by the user. Idea: Add 'term' to the word secrets that tells about the help button.

# Secrets
- 'Your own account' seems redundant
   - [x] [Moved to issue] ~~#241~~
   - [x] [same issue as above] Why would I put it on its own account?
      - Supposing you make the tests run on your account and then you leave the project and delete your account? The tests will fail.
   - [x] [described that the tests delete the project at the end] Does it make a new project once or keep making new projects? don't these projects build up?
      - [x] Change description of what tests do to 'will automatically make a temporary Project' ("temporary" is important)
   - [x] Maybe put info about what tests literally do on this page instead/as well.
   - [x] Screenshots may help [follow up needed about what kind of screenshots]. [Moved to #240]
- [x] Where will I see the new project being created?
   - A misunderstanding about what it looks like when the automated process happens.
- Handle 1 of 2 situations:
   - [x] You are working with a team or organization. Options:
      - [x] [Moved to #242.] Add "Discuss which account to use with your team"?
         - "Discuss with your team if you will have an account just for automated testing." Note: They do need to know why they'd make one decision over another, though. We don't have a good concise description of that yet.
      - [x] [Moved to #243.] Prevent someone who hasn't discussed with their team from adding org secrets?
         - Feedback: Maybe don't let them set up secrets in this case. Reply: Whoever is setting it up for the first time does need to set up secrets.
   2. You are working alone.

**Comment by plocket** [comment]
All items completed or made into new issues.
