### ISSUE TITLE
Create an interview to help a developer set up testing for their repo (MVP)

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-ALAutomatedTestingTests#37]
Ideally, they leave the interview as little as possible.

## TODO functionality:
- [x] Get username, repo name, personal access token
- [x] Parse username and repo name from repo url
- [x] Get email, password, ... playground id from an interview url
- [x] Set secrets (maybe done. no way to test yet.)
- [x] Copy and transform files
- [x] Push to? New branch and PR? Or to default branch?

## TODO validation:
- [x] Check repo address is sensical github address
- [x] Check user and repo exist
- [x] Check that user has permissions on the repo
- [x] Check that interview url is of correct type

## TODO discuss refactoring:
~Split into GitHubAuth, GitHubSecrets, GitHubPush, GitHubTestInstaller?~ Have [PyGithub](https://pygithub.readthedocs.io/en/latest/apis.html) now.
~Split into GithubSecrets, GitHubTestInstaller? (PyGithub does not yet handle secrets) May not be worth it at this point.~

**Comment by plocket** [comment]
Possible future features:
- [ ] Org secrets
- [ ] Set secrets for multiple repos

**Comment by plocket** [comment]
Found [secrets in PyGithub](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=secret#github.Repository.Repository.create_secret)! I must have missed them before somehow!
